CREATE TABLE "C##CLOUD$SERVICE"."CLOUD_SERVICE_TEMPLATE" SHARING=METADATA 
   (	"TEMPLATE" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"EXCL_LOCK" CHAR(1) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SHR_LOCK_CNT" NUMBER NOT NULL ENABLE, 
	 CHECK (excl_lock in ('Y', 'N')) ENABLE, 
	 CHECK (shr_lock_cnt >= 0) ENABLE, 
	 PRIMARY KEY ("TEMPLATE")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/

/
ALTER TABLE "C##CLOUD$SERVICE"."CLOUD_SERVICE_TEMPLATE" ADD CHECK (excl_lock in ('Y', 'N')) ENABLE
/
ALTER TABLE "C##CLOUD$SERVICE"."CLOUD_SERVICE_TEMPLATE" ADD CHECK (shr_lock_cnt >= 0) ENABLE
/
ALTER TABLE "C##CLOUD$SERVICE"."CLOUD_SERVICE_TEMPLATE" ADD PRIMARY KEY ("TEMPLATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX"  ENABLE
/